#A short introduction to numpy arrays

For a more detailed Tutorial see: http://wiki.scipy.org/Tentative_NumPy_Tutorial

or the documentation: http://www.numpy.org/

Numpy is the fundamental package for scientific computing with Python. It provides a huge range of scientific function like fourier transformations and random number generators.

This short introduction just shows some basics on how to work with numpy arrays.

First we need to load the numpy library. It is common to use the namespace "np"

In [16]:
import numpy as np

##Basics

There are different ways to create a numpy array. A easy one is:

In [17]:
a = np.array([1,2,3])

here the numbering of the n positions starts with 0. We can access a value of our array using:

In [18]:
print a[0]

1


if we want to access multiple value we can choose a range:

In [19]:
print a[0:2]

[1 2]


the begining is included and the end is excluded (0 until n-1). If no begining or end is given the beginnig/end of the array is assumed:

In [20]:
print a[:2]
print a[2:]
print a[:]

[1 2]
[3]
[1 2 3]


You can also access the values from the back using negativ numbers:

In [21]:
print a[-1]
print a[:-1]

3
[1 2]


##$N^M$ arrays

aswell you can create differently shaped arrays:

In [22]:
a = np.array([[1,2,3],
             [4,5,6]])
print a

[[1 2 3]
 [4 5 6]]


to access a value of the array we will proceed simular to the case of the 1D array, asking for row and column:

In [23]:
a[0,0]

1

don't use "a[0][0]" event though it works!!! (because this will first create the array a[0] which will need RAM and time)

now we can use the ":" operator to access areas of our matrix similar to the examples above:

In [24]:
print a[:,0]
print a[0,:]
print a[0,:2]

[1 4]
[1 2 3]
[1 2]


##Using boolean arrays to access an array

numpy arrays can also be accessed using boolean arrays. In this example we want to have all elements of the array (a) that are even. First of all we have a look at the boolean array:

In [25]:
print a%2==0     # % is the modulus operator

[[False  True False]
 [ True False  True]]


now we can use this array to access the values of our array:

In [26]:
print a[a%2==0]

[2 4 6]


###second example (a bit more complicated)

we will create some data:

In [27]:
data = np.array([[1,2,3,4,5],
                [10,5,7,3,8]])

this could be some measured data where for each x-value (1,2,3,4,5) was measured a value. Now we want to pick all value for x larger than 2:

In [28]:
dataLargerThanTwo = data[:,data[0,:]>2]
print dataLargerThanTwo

[[3 4 5]
 [7 3 8]]


to find the maximum value and its position:

In [34]:
datamax=np.max(data)
print datamax

10


In [30]:
datamaxpos=np.where(data==data.max())
print datamaxpos
# Output: (array([1]), array([0])) # the first one is the row index, the second is the column

(array([1]), array([0]))


##Importing and saving data

Numpy provides a function to import data files. The file needs to be a NxM - Matrix. Commends are set with '#' and commas need to be '.'. You can set a delimiter with the 'delimiter=' parameter.

In [31]:
data = np.loadtxt("./dataExample/loadtxtExample.dat")
print data

IOError: [Errno 2] No such file or directory: './dataExample/loadtxtExample.dat'

NxM - Arrays can be saved using the savetxt function.

In [ ]:
np.savetxt("./dataExample/savetxtExample.dat", data, delimiter=='\t')